#######################################################
# 
# IPersistor.py
# Python implementation of the Interface IPersistor
# Generated by Enterprise Architect
# Created on:      18-feb-2022 21:05:20
# Original author: paula
# 
#######################################################
class IPersistor:

    def persist(self, *args, **kwargs):
        return self

    def drop(self, *args, **kwargs):
        return self

    def select(self, *args, **kwargs):
        return self
