#######################################################
# 
# Persistor.py
# Python implementation of the Class Persistor
# Generated by Enterprise Architect
# Created on:      18-feb-2022 21:05:20
# Original author: paula
# 
#######################################################
from com.nttdata.dgi.crud.IPersistor import IPersistor
from com.nttdata.dgi.persistence.persistor_type import PersistorType


class PersistorArgumentError(ValueError):
    pass


class Persistor(IPersistor):

    type: PersistorType

    def __init__(self):
        self.type = PersistorType.NONE
        return

    def persist(self, *args, **kwargs):
        return self

    def drop(self, *args, **kwargs):
        return self

    def select(self, *args, **kwargs):
        return self
